release-repo: git@github.com:CDLUC3/mrt-doc.git
repositories:
  # Documentation
  - repo: git@github.com:CDLUC3/mrt-doc.git
  - repo: git@github.com:CDLUC3/mrt-doc-private.git
  # Java Code
  - repo: git@github.com:CDLUC3/mrt-inventory.git
  - repo: git@github.com:CDLUC3/mrt-ingest.git
  - repo: git@github.com:CDLUC3/mrt-audit.git
  - repo: git@github.com:CDLUC3/mrt-replic.git
  - repo: git@github.com:CDLUC3/mrt-store.git
  - repo: git@github.com:CDLUC3/mrt-cloud.git
  - repo: git@github.com:CDLUC3/mrt-core2.git
  # Java and Ruby
  - repo: git@github.com:CDLUC3/mrt-zk.git
  # Java code - ad hoc tools
  # - repo: git@github.com:CDLUC3/File-Analyzer.git
  - repo: git@github.com:CDLUC3/mrt-box.git
  - repo: git@github.com:CDLUC3/mrt-maint.git
  # Ruby code
  - repo: git@github.com:CDLUC3/mrt-dashboard.git
  - repo: git@github.com:CDLUC3/mrt-ingest-ruby.git
  - repo: git@github.com:CDLUC3/mrt-admin-lambda.git
  - repo: git@github.com:CDLUC3/mrt-integ-tests.git
  - repo: git@github.com:CDLUC3/uc3-ssm.git
  - repo: git@github.com:CDLUC3/mrt-cron.git
  - repo: git@github.com:CDLUC3/mrt-atom.git
  - repo: git@github.com:CDLUC3/s3-sinatra.git
  - repo: git@github.com:CDLUC3/mrt-admin-sinatra.git
  # Config code
  - repo: git@github.com:CDLUC3/mrt-tomcat.git
  - repo: git@github.com:cdlib/mrt-ingest-profile.git
    branches:
    - production
    - stage
  - repo: git@github.com:CDLUC3/merritt_ldap_tools.git
  # DevOps code
  - repo: git@github.com:CDLUC3/mrt-ansible-service-restart.git
  # DevOps code
  - repo: git@github.com:CDLUC3/mrt-sceptre.git
  - repo: git@github.com:CDLUC3/mrt-tomcat-deploy.git
  - repo: git@github.com:CDLUC3/mrt-service-release-manifest.git
  # Docker Code
  - repo: git@github.com:CDLUC3/merritt-docker.git
  # remove mrt-tind-harvester from tagging until it is active again
  # - repo: git@github.com:CDLUC3/mrt-tind-harvester.git
  # Python code
  - repo: git@github.com:CDLUC3/uc3-etds.git
    branches:
    - production
    - stage
  - repo: git@github.com:CDLUC3/mrt-repo-tagger.git
  - repo: git@github.com:CDLUC3/mrt-locust.git  
  # Soon to be deprecated code - will be retired when a Yaml based Nuxeo management system is ready
  - repo: git@github.com:cdlib/mrt-dashboard-config.git
sprint-template: >
  ## Major accomplishments:

deploy-template: >
  ## Service(s)


  ## Servers affected


  ## Change Description


  ## Github issue

  Link(s)
  -

  ## Source Code:

  Link(s) to tagged release(s)
  -

  ## Infrastructure Changes to support software (ALB, EFS, etc)


  ## Jenkins: (if applicable)

  ### Build name/number

  ### Build URL


  ## Upgrade Steps (if applicable)
  - [ ] Action Step 1
