release-repo: git@github.com:CDLUC3/mrt-doc.git
repositories:
  # Documentation
  - repo: git@github.com:CDLUC3/mrt-doc.git
  - repo: git@github.com:CDLUC3/mrt-doc-private.git
  # Java Code
  - repo: git@github.com:CDLUC3/mrt-inventory.git
  - repo: git@github.com:CDLUC3/mrt-ingest.git
  - repo: git@github.com:CDLUC3/mrt-audit.git
  - repo: git@github.com:CDLUC3/mrt-replic.git
  - repo: git@github.com:CDLUC3/mrt-store.git
  - repo: git@github.com:CDLUC3/mrt-cloud.git
  - repo: git@github.com:CDLUC3/mrt-zoo.git
  - repo: git@github.com:CDLUC3/mrt-core2.git
  - repo: git@github.com:CDLUC3/cdl-zk-queue.git
  # Build functions
  - repo: git@github.com:CDLUC3/mrt-jenkins.git
  # Java code - ad hoc tools
  - repo: git@github.com:CDLUC3/File-Analyzer.git
  # Ruby code
  - repo: git@github.com:CDLUC3/mrt-dashboard.git
  - repo: git@github.com:CDLUC3/mrt-ingest-ruby.git
  - repo: git@github.com:CDLUC3/mrt-admin-lambda.git
  - repo: git@github.com:CDLUC3/mrt-integ-tests.git
  - repo: git@github.com:CDLUC3/uc3-ssm.git
  - repo: git@github.com:CDLUC3/mrt-cron.git
  # Groovy code
  - repo: git@github.com:CDLUC3/mrt-jenkins.git
  # Configuration code
  - repo: git@github.com:CDLUC3/tomcat8_catalina_base.git
    branches:
    - mrt-audit01x2-prd
    - mrt-audit01x2-stg
    - mrt-audit02x2-prd
    - mrt-audit02x2-stg
    - mrt-audit03x2-prd
    - mrt-audit04x2-prd
    - mrt-ingest01x2-prd
    - mrt-ingest01x2-stg
    - mrt-ingest02x2-prd
    - mrt-ingest02x2-stg
    - mrt-ingest03x2-prd
    - mrt-inv01x2-prd
    - mrt-inv01x2-stg
    - mrt-inv02x2-prd
    - mrt-inv02x2-stg
    - mrt-oai01x2-prd
    - mrt-oai01x2-stg
    - mrt-replic01x2-prd
    - mrt-replic01x2-stg
    - mrt-replic02x2-prd
    - mrt-replic02x2-stg
    - mrt-replic03x2-prd
    - mrt-replic04x2-prd
    - mrt-store01x2-prd
    - mrt-store01x2-stg
    - mrt-store02x2-prd
    - mrt-store02x2-stg
    - mrt-store03x2-prd
    - mrt-store04x2-prd
    - mrt-sword01x2-prd
    - mrt-sword01x2-stg
  - repo: git@github.com:CDLUC3/mrt-tomcat.git
  - repo: git@github.com:cdlib/mrt-ingest-profile.git
    branches:
    - production
    - stage
  # Docker Code
  - repo: git@github.com:CDLUC3/merritt-docker.git
  # Other code
  - repo: git@github.com:CDLUC3/mrt-store-admin.git
    branches:
    - master
  # remove mrt-tind-harvester from tagging until it is active again
  # - repo: git@github.com:CDLUC3/mrt-tind-harvester.git
  - repo: git@github.com:CDLUC3/merritt-manifest.git
    branches:
    - master
  # Python code
  - repo: git@github.com:CDLUC3/uc3-etds.git
    branches:
    - production
    - stage
  - repo: git@github.com:CDLUC3/mrt-repo-tagger.git
  # Shell script code
  - repo: git@github.com:CDLUC3/uc3-aws-cli.git
  # Soon to be deprecated code - will be retired when a Yaml based Nuxeo management system is ready
  - repo: git@github.com:cdlib/mrt-dashboard-config.git
sprint-template: >
  ## Major accomplishments:

deploy-template: >
  ## Service(s)


  ## Servers affected


  ## Change Description


  ## Github issue

  Link(s)
  -

  ## Source Code:

  Link(s) to tagged release(s)
  -

  ## Infrastructure Changes to support software (ALB, EFS, etc)


  ## Jenkins: (if applicable)

  ### Build name/number

  ### Build URL


  ## Upgrade Steps (if applicable)
  - [ ] Action Step 1
